# Generated by Django 4.1.9 on 2025-06-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hair', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lifespan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lifespan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Temperament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperament', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trainability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trainability', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dogs.color')),
                ('hair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dogs.hair')),
                ('lifespan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dogs.lifespan')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dogs.size')),
                ('temperament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dogs.temperament')),
                ('trainability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dogs.trainability')),
            ],
        ),
    ]
